### ISSUE TITLE
body content is crammed to the left of the screen in chapter2:watchers

### ISSUE THREAD

**Issue by patlecat** [PacktPublishing/Full-Stack-Vue.js-2-and-Laravel-5#3]
Adding the following to CSS the content of the page is crammed to the left of the screen when the modal opens, but why?

```CSS
body.modal-open {
    overflow: hidden;
    position: fixed;
}
```

**Comment by anthonygore** [comment]
Sorry for the late reply. That shouldn't happen. Can you link me to your code and I will attempt to debug for you.

**Comment by meeglos** [comment]
I solved that by  removing the second line, it should look like this: 
```css
body.modal-open {
    overflow: hidden;
}
```
